name: ubuntu-latest

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - release
    tags-ignore:
      - v*
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/ubuntu-latest.yml'
      - '!.github/workflows/build-all.yml'
      - '!.github/workflows/test-dist.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
    with:
      os: ubuntu-latest

  test-dist:
    needs: [build-all]
    uses: ./.github/workflows/test-dist.yml
    with:
      os: ubuntu-latest

  update-website:
    needs: [test-dist]
    # If the commit is tagged with a version (e.g. "v1.0.0"),
    # that means a new release has been created.
    # Update the website to show new version.
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/update-website.yml
    secrets: inherit

  publish-snapcraft:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test-dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-ubuntu-latest
          path: ./snap
      - name: Push to snapcraft.io
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.PANERON_SNAPCRAFT_TOKEN }}
        run: |
          echo "${SNAPCRAFT_TOKEN}" > .snapcraft_token
          snapcraft login --with .snapcraft_token
          snapcraft push --release=stable snap/*.snap
