name: update-website

on:
  workflow_call:
    secrets:
      GH_PANERON_CI_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  trigger-website-build:
    name: Trigger website build
    runs-on: ubuntu-latest

    concurrency:
      group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    steps:
      - name: Dispatch update-website event
        run: |
          curl \
            -X POST \
            --fail-with-body \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_PANERON_CI_TOKEN}" \
            https://api.github.com/repos/paneron/extensions.paneron.org/dispatches \
            -d '{"event_type":"update-website","client_payload":{}}'
        env:
          GH_PANERON_CI_TOKEN: ${{ secrets.GH_PANERON_CI_TOKEN }}

